version: '3'

services:
  app-server:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: always
    networks:
      - rede-docker

networks:
  rede-docker: