version: '3'

services:
  app-server-java:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    restart: always
    networks:
      - rede-docker

networks:
  rede-docker: